### ISSUE TITLE
Non-existent function - cpt_is_valid_url

### ISSUE THREAD

**Issue by challengewpdev** [okeowobabz/correct-permalinks#2]
This function does not exist? - [cpt_is_valid_url](https://github.com/okeowobabz/correct-permalinks/blob/ddd11c2e88a568fc87cfc52c6c313223a903664e/correct-permalinks.php#L44)

**Comment by okeowobabz** [comment]
Oops, I messed with the naming I have updated it -[cpt_is_valid_url](https://github.com/okeowobabz/correct-permalinks/blob/ddd11c2e88a568fc87cfc52c6c313223a903664e/correct-permalinks.php#L26)
